runtime: nodejs14
service: storefront-api
entrypoint: cross-env VSF_BIND_PORT=$PORT node dist/src/index.js
env_variables:
  NODE_APP_INSTANCE: imp
  NODE_CONFIG_ENV: test
  VSF_BIND_HOST: 0.0.0.0
  VSF_REDIS_HOST: 10.244.152.179
  VSF_REDIS_PORT: 6379
instance_class: F4
automatic_scaling:
  max_instances: 2
