runtime: nodejs14
service: storefront-api
entrypoint: cross-env VSF_BIND_PORT=$PORT node dist/src/index.js
env_variables:
  NODE_APP_INSTANCE: imp
  NODE_CONFIG_ENV: gae
  VSF_BIND_HOST: 0.0.0.0
instance_class: F4
automatic_scaling:
  max_instances: 2
vpc_access_connector:
  name: 'projects/icmaa-vsf-poc-02/locations/europe-west1/connectors/icmaa-vsf-poc-02'
