version: '3.0'
services:

  elasticsearch:
    image: elasticsearch:8.5.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      http.max_content_length: 512mb
      discovery.type: single-node
      xpack.security.enabled: "false"

  app:
    depends_on:
      - elasticsearch
