name: Continuous Delivery

on:
  push:
    branches:
      - master
      - develop
      - develop-*
      - build/*
      - gcloud/*

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env:
          - MANDANT: imp

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Get repository-name, branch-name and version-base-name
        run: |
          echo "APP=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "VERSION_BASE_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV

      - name: Get environment by branch
        run: |
          echo "ENV=$(if [ ${{ env.BRANCH_NAME }} = "master" ]; then echo "production"; else echo "test"; fi)" >> $GITHUB_ENV

      - name: Checkout "icmaa/shop-workspace" repo
        run: |
          rm -rf shop-workspace
          export CONFIG_BRANCH=$(if [ "${{ env.BRANCH_NAME }}" != "master" ]; then echo "-b develop"; fi)
          git clone --no-tags --depth 1 https://${{ secrets.PAT }}@github.com/icmaa/shop-workspace $CONFIG_BRANCH

      - name: Sync config JSON files
        run: rsync -r ./shop-workspace/template/${{ env.APP }}/ ./

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Install dependencies
        run: yarn

      - name: Build "${{ env.APP }}"
        timeout-minutes: 15
        run: yarn build
        env:
          NODE_CONFIG_ENV: gae
          NODE_APP_INSTANCE: ${{ matrix.env.MANDANT }}

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_VSF_SA_KEY }}
          project_id: ${{ secrets.GCP_VSF_PROJECT_ID }}
          version: ${{ env.VERSION_BASE_NAME }}-${GITHUB_SHA}
