name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:

  test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run existing tests and linting
        run: |
          yarn
          yarn test:unit
          yarn lint
          yarn lint-gql
        env:
          CI: true
